# roles/postgresql/tasks/main.yml
- name: Добавление репозитория PG  в sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    create: true

- name: Загрузка PostgreSQL ключа 
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Обновление кэша пакетов
  apt:
    update_cache: yes

- name: Установка PostgreSQL-{{ pg_version }}
  apt:
    name: postgresql-{{ pg_version }}
    state: present

- name: Контроль работы службы
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Настройка базы данных 
  block:
    - name: Создание пользователя {{ db_user }}
      command:
        runuser -l postgres -c "psql -c \"CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';\""
      failed_when: false

    - name: Создание базы {{ db_name }}
      command:
        runuser -l postgres -c "psql -c \"CREATE DATABASE {{ db_name }} OWNER {{ db_user }};\""
      failed_when: false

    - name: Предоставление привилегий пользователя {{ db_user }} к базе {{ db_name }}
      command:
        runuser -l postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};\""
      failed_when: false

- name: Настройка прав доступа к схеме Public пользователя {{ db_user }}
  block:
    - name: ALL ON
      command: 
        runuser -l postgres -c "psql -U postgres -d {{ db_name }} -c \"GRANT ALL ON SCHEMA public TO {{ db_user }};\""

    - name: CREATE
      command: 
        runuser -l postgres -c "psql -U postgres -d {{ db_name }} -c \"GRANT CREATE ON SCHEMA public TO {{ db_user }};\""

    - name: ALTER SCHEMA
      command: 
        runuser -l postgres -c "psql -U postgres -d {{ db_name }} -c \"ALTER SCHEMA public OWNER TO {{ db_user }};\""

- name: Контроль наличия файла {{ db_backup }}
  file:
        path: /home/{{ ansible_user }}/{{ db_backup }}
        state: file
        mode: "0755"

- name: Импорт базы данных постов
  command: >
    psql -U {{ db_user }} -h {{ db_host }} -d {{ db_name }} -f ~/{{ db_backup }}
  environment:
    PGPASSWORD: "{{ db_password }}"
  become: false
  